version: '3'
services:
  rasanlg:
    build:
      context: ./rasa/nlg
      dockerfile: Dockerfile
      args:
        env: dev
    command:
      - /bin/bash
      - -c
      - |
          python -m rasa_nlu.train -c config/config_spacy_duckling.yml --data projects/default -o models/nlu --project default --verbose
          python -m rasa_nlu.server --port 5000 -c /app/config/config_spacy_duckling.yml --path models/nlu --response_log /app/logs --debug
    ports:
      - '5000:5000'
    volumes:
      - ./rasa/nlg/app/projects:/app/projects
      - ./rasa/nlg/app/config/:/app/config
      - ./rasa/nlg/app/models/:/app/models
      - ./data/rasa/nlg/logs:/app/logs
  duckling:
    image: rasa/duckling:latest
  redis:
    image: redis:4.0.11-alpine


