version: '3'
services:
  rasanlu:
    restart: unless-stopped
    build:
      context: ./rasa/nlu
      dockerfile: Dockerfile
      args:
        env: dev
    command:
      - /bin/bash
      - -c
      - |
          python -m rasa_nlu.train -c config/default.yml --data projects/default/nlu_data.json -o models/nlu --project default --verbose
          python -m rasa_nlu.server --port 5000 -c /app/config/default.yml --path models/nlu --response_log /app/logs --debug
    ports:
      - '5000:5000'
    #volumes:
    #  - ./rasa/nlu/app/projects:/app/projects
    #  - ./rasa/nlu/app/config/:/app/config
    #  - ./rasa/nlu/app/models/:/app/models
    #  - ./data/rasa/nlu/logs:/app/logs
  duckling:
    restart: unless-stopped
    image: rasa/duckling:latest
  #redis:
  #  image: redis:4.0.11-alpine
  #proxy:
  #  image: traefik:v1.6
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  labels:
  #    - traefik.frontend.rule=Host:${DOMAIN}
  #    - traefik.enable=true
  #    - traefik.port=80
  #flower:
  #  image: totem/celery-flower-docker
  #  environment:
  #    - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
