language : "en"

pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
  - name: "ner_duckling_http"
    url: "http://duckling:8000"
    dimensions:
    - email
    - number
    - amount-of-money
